### ISSUE TITLE
English language as go-to option for code

### ISSUE THREAD

**Issue by nerder** [kettanaito/naming-cheatsheet#28]
First of all, thank you so much for taking the time on doing this work.

I would like to open up a question about the use of English language in code, since I do think that is not always the case.

English should be considered as a good default, but in terms of importance the business language should comes first. It's not uncommon to see functions, types or variables with a mixed approach of business language and English and I do believe that this should not considered an anti-pattern but enforced instead, maybe with a `TRANSLATION.md` or `GLOSSARY.md` somewhere in the project. 

While it's true that for consistency is very important, the final objective of labeling (as in variable, functions, type etc) should be to convey as much meaning as possible. 

The first step to build a comprehensive ubiquitous language which can serve as a bridge between tech and business should come from the subject-matter expert which might or might not be a native English speaker, code should simply follow as a simple tool used to describe and model the world.

Please go ahead in brings your point of view as we can discuss this further.

**Comment by threeal** [comment]
Talking about English for the main language in code naming convention, just look at how many language syntax and libraries that using English for the code naming convention. Actually it's fine when you want to use other language so your colleagues that don't used to English could understand it. But it would be better to be consistent on using English.

Actually i don't know how a code should be written in business context. But as far as i know, what inside a code does not have any meaning for a non programmer, they could just ignore it and let the programmer do the things. And i think, programmer should be used to English, knowing how many languages, libraries, references, and documentations that also written in English.

Just look at this JavaScript example:

```javascript
for (const manzana of manzanas) {
  if (manzana.estaEstropeada()) {
    manzana.comer();
  }
}
```

It would be unusual to read it as "for manzana of manzanas", instead of "para manzana de manzanas", or "for apple of apples", but there is neither `para` nor `de` in JavaScript syntax. The same also works for "if manzana esta estropeada". Also that example is written using Spanish, that doesn't have a lot of differences from the English. So what about other languages that's far from English? like Chinese? Japanese? or even Arabic which written from right to left instead of left to right like English?

**Comment by nerder** [comment]
This is very good point thank you for that!

Please don't take me wrong, my point is not to write code entirely in another language, but it might be possible that business words slips into the code and they might or might not be in English.

As an example, imagine you are developing the system that is in charge of emitting residency permit for people in Spain the code you may write will be:

```javascript

class EmpadronamientoRepository {
    EmpadronamientoCertificate emit();
}
```

I will argue that `empadronamiento` as a keyword works better than the literal English translation `census` (or `certificate or residency`) as it bring more value. In fact this is also the case when people speaks in an English conversation about this kind of things. People tend to use the Spanish word for it, as trying in translate the concept will be way more lengthy and exposed to possible misunderstanding. My take is that code should do the same not forcing English over a concept which is better to understand in it's original form, and this happens a lot when trying to model in code something in a very technical domain.

This is my head will work for every language in it's _romanized_ form (ie: [Romanization of Japanese](https://en.wikipedia.org/wiki/Romanization_of_Japanese) , [Romanization of Hebrew](https://en.wikipedia.org/wiki/Romanization_of_Hebrew) or [Romanization of Arabic](https://en.wikipedia.org/wiki/Romanization_of_Arabic)*)


_*NOTE: for Arabic this might not work, as it will need transliteration which might not be possible, but i'm not sure_

**Comment by threeal** [comment]
I understand your points. If those are the cases, then it would be fine to use the non-English word as the variable name. But i also understand why the author enforce to use English when naming a variables or functions.

**Comment by threeal** [comment]
I understand your points. If those are the cases, then it would be fine to use the non-English word as the variable name. But i also understand why the author enforce to use English when naming a variables or functions.

**Comment by kettanaito** [comment]
It so happened that English dominates the engineering medium. What I tried to say in the "Use English language" section is to be respectful of that, understanding that many people learn engineering in English. You can (and likely should) prefer domain-specific terms if those bring more value to your code. Do that by all means. 

The main reason for this section to exist comes from my personal experience where bringing foreign words into code was simply a sign of lazy development and a disrespectful attitude towards foreign team members that need to spend additional time understanding what somebody else meant in the code. Programming is hard as it is, let's at least rule the grammatical and syntactical challenges out of code. I think that's a reasonable default to go by. 

I still stand by that section and don't see much value in changing it. It's there to prevent developers from falling into bad habits of naming everything how _they_ think is natural (in terms of language). In that light, the section achieves its purpose.
