### ISSUE TITLE
Question about the `is` prefix.

### ISSUE THREAD

**Issue by tcK1** [kettanaito/naming-cheatsheet#3]
What do we think about the usage of the `is` prefix with gerund variables. For example, `loading`.

We could use the prefix:

```js
if (isLoading) {
  doSomething();
}
```

But does it seems a bit redundant, or is it just me? 😆 

```js
if (loading) {
  doSomething();
}
```

**Comment by kettanaito** [comment]
Hey, @tcK1. 

There's no hard rule on this, pick whichever method reads the best for your and your team. Consistency is the key here.

I personally don't mind both `isLoading` and `loading`.

**Comment by sowizz** [comment]
Hi, I don't want to open a new issue regarding the `is` prefix, so I'll ask here: what do you suggest to use as a prefix with helper variables such as `<missing_prefix>itemsLoaded`?

```js
const areItemsLoaded = true
```

or 

```js
const isItemsListLoaded = true
```
?

**Comment by kettanaito** [comment]
@sowizz how about `hasItems`?

**Comment by sowizz** [comment]
I'm not sure, I'd say `hasItems` would be better for:
```js
const hasItems = items.length > 0
``` 
in my case the helper variable says whether the items were fetched from the server, so the `items` array might as well be empty and that variable would still have `true` as a value.

**Comment by seahindeniz** [comment]
I believe using it on functions that operates something is more convenient because when you have a function called `isSomethingVisible`, in the same context where you need to name the variable, can lead to confusion. So I believe there should be a strict distinction between them to understand its purpose without checking its code/color/type. 

Here's a case from a vanilla js code that operates on DOM
```js
//util.js
const isAdVisible = () => someElement.classList.contains(VISIBILITY);

//imports
const adVisibility = isAdVisible();
const visibility = isAdVisible(); // if called in a singular context
const visible = isAdVisible();
```
